import InvoiceType from "../types/InvoiceType";

const SampleInvoiceData: InvoiceType[] = [
  {
    invoiceId: 1,
    performerUsername: 'Leyla',
    dateAttempted: 'Mar 01 2025',
    paymentMethod: '1520 **** **** 2081',
    amountPaid: 500,
    status: 'PENDING',
    invoiceDate: 'March 6, 2025',
    dueDate: 'March 7, 2025',
    clientName: 'David Brooke',
    clientEmail: 'davidbrooke@gmail.com',
    streetAddress: '9029 River Rd',
    city: 'Provo',
    state: 'Utah',
    zip: 84602,
    eventName: 'Graduation Party',
    eventDate: 'Mar 10, 2025',
    amountDue: 500,
  },
  {
    invoiceId: 2,
    performerUsername: 'Faud',
    dateAttempted: 'Feb 28 2025',
    paymentMethod: '1520 **** **** 2081',
    amountPaid: 200,
    status: 'PAID',
    invoiceDate: 'March 6, 2025',
    dueDate: 'March 7, 2025',
    clientName: 'David Brooke',
    clientEmail: 'davidbrooke@gmail.com',
    streetAddress: '9029 River Rd',
    city: 'Provo',
    state: 'Utah',
    zip: 84602,
    eventName: 'Graduation Party',
    eventDate: 'Mar 10, 2025',
    amountDue: 200,
  },
  {
    invoiceId: 3,
    performerUsername: 'Ali',
    dateAttempted: 'Jan 27 2025',
    paymentMethod: '1520 **** **** 2081',
    amountPaid: 100,
    status: 'PAID',
    invoiceDate: 'March 6, 2025',
    dueDate: 'March 7, 2025',
    clientName: 'David Brooke',
    clientEmail: 'davidbrooke@gmail.com',
    streetAddress: '9029 River Rd',
    city: 'Provo',
    state: 'Utah',
    zip: 84602,
    eventName: 'Graduation Party',
    eventDate: 'Mar 10, 2025',
    amountDue: 100,
  },
  {
    invoiceId: 4,
    performerUsername: 'Ali',
    dateAttempted: 'Jan 26 2025',
    paymentMethod: '1520 **** **** 2081',
    amountPaid: 100,
    status: 'FAILED',
    invoiceDate: 'March 6, 2025',
    dueDate: 'March 7, 2025',
    clientName: 'David Brooke',
    clientEmail: 'davidbrooke@gmail.com',
    streetAddress: '9029 River Rd',
    city: 'Provo',
    state: 'Utah',
    zip: 84602,
    eventName: 'Graduation Party',
    eventDate: 'Mar 10, 2025',
    amountDue: 100,
  }
];

export default SampleInvoiceData;