import PaymentProps from "../types/PaymentsType"

const samplePaymentData: PaymentProps[] = [
  {
    status: 'Received',
    amount: 1367,
    event: 'Sunset Music Festival',
    eventManager: 'Jenny Wilson',
    dateTime: 'Apr 15, 2025, 8:30 pm',
    gigType: 'SOLO',
  },
  {
    status: 'Pending',
    amount: 2000,
    event: 'Sunset Music Festival',
    eventManager: 'Jenny Wilson',
    dateTime: 'Apr 15, 2025, 8:30 pm',
    gigType: 'BAND',
  }, 
  {
    status: 'Received',
    amount: 988,
    event: 'Sunset Music Festival',
    eventManager: 'Jenny Wilson',
    dateTime: 'Apr 15, 2025, 8:30 pm',
    gigType: 'SOLO',
  },
  {
    status: 'Received',
    amount: 1600,
    event: 'Sunset Music Festival',
    eventManager: 'Jenny Wilson',
    dateTime: 'Apr 15, 2025, 8:30 pm',
    gigType: 'SOLO',
  }, 
  {
    status: 'Received',
    amount: 1798,
    event: 'Sunset Music Festival',
    eventManager: 'Jenny Wilson',
    dateTime: 'Apr 15, 2025, 8:30 pm',
    gigType: 'SOLO',
  },
  {
    status: 'Received',
    amount: 1367,
    event: 'Sunset Music Festival',
    eventManager: 'Jenny Wilson',
    dateTime: 'Apr 15, 2025, 8:30 pm',
    gigType: 'SOLO',
  },
  {
    status: 'Pending',
    amount: 2000,
    event: 'Sunset Music Festival',
    eventManager: 'Jenny Wilson',
    dateTime: 'Apr 15, 2025, 8:30 pm',
    gigType: 'BAND',
  }, 
  {
    status: 'Received',
    amount: 988,
    event: 'Sunset Music Festival',
    eventManager: 'Jenny Wilson',
    dateTime: 'Apr 15, 2025, 8:30 pm',
    gigType: 'SOLO',
  },
  {
    status: 'Received',
    amount: 1367,
    event: 'Sunset Music Festival',
    eventManager: 'Jenny Wilson',
    dateTime: 'Apr 15, 2025, 8:30 pm',
    gigType: 'SOLO',
  },
  {
    status: 'Pending',
    amount: 2000,
    event: 'Sunset Music Festival',
    eventManager: 'Jenny Wilson',
    dateTime: 'Apr 15, 2025, 8:30 pm',
    gigType: 'BAND',
  }, 
  {
    status: 'Received',
    amount: 1798,
    event: 'Sunset Music Festival',
    eventManager: 'Jenny Wilson',
    dateTime: 'Apr 15, 2025, 8:30 pm',
    gigType: 'SOLO',
  },
];

export default samplePaymentData;